version: 0.0
os: linux
files:
  - source: api-1.0.0-SNAPSHOT.jar
    destination: /home/ubuntu
  - source: composite-service-1.0.0-SNAPSHOT.jar
    destination: /home/ubuntu
  - source: order-1.0.0-SNAPSHOT.jar
    destination: /home/ubuntu
hooks:
  BeforeInstall:
    - location: stopApp.sh
      timeout: 180
  AfterInstall:
    - location: runApp.sh
      timeout: 180