version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - echo Nothing to do in pre_build phase
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - api/build/libs/api-1.0.0-SNAPSHOT.jar
    - composite-service/build/libs/composite-service-1.0.0-SNAPSHOT.jar
    - demo/build/libs/demo-0.0.1-SNAPSHOT.jar
    
