logging:
  level:
    root: INFO
    com.example: DEBUG

spring:
  profiles:
    active: "prod"
  main:
    allow-bean-definition-overriding: true

server.port: 9001

---

spring:
  profiles: dev

amazon.dynamodb.endpoint: http://localhost:8000

app:
  restaurant-manager:
    host: localhost
    port: 3000
    base:

amazon.aws:
  accesskey: akey
  secretkey: skey
  region: us-east-1

---

spring:
  profiles: prod

amazon.dynamodb.endpoint: http://dynamodb.us-east-1.amazonaws.com

app:
  restaurant-manager:
    host: 3.88.210.26
    port: 8080
    base: RestaurantManager-0.0.1

amazon.aws:
  accesskey: AKIA6JUAEY3OUORY2Q7V
  secretkey: 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
  region: us-east-1


