logging:
  level:
    root: INFO
    com.example.demo: DEBUG

spring:
  profiles:
    active: "dev"
  main:
    allow-bean-definition-overriding: true

service.port: 7000

app:
  order-service:
    host: localhost
    port: 9001

spring.devtools.restart.additional-paths: static/**,templates/**

server.error.whitelabel.enabled: false

---

spring:
  profiles: dev

amazon.dynamodb.endpoint: http://localhost:8000

amazon.aws:
  accesskey: akey
  secretkey: skey
  region: us-east-1

---

spring:
  profiles: prod

amazon.dynamodb.endpoint: http://dynamodb.us-east-1.amazonaws.com

amazon.aws:
  accesskey: akey
  secretkey: skey
  region: us-east-1


